main: pl.trollcraft.Skyblock.Skyblock
authors:
  - Pijok
  - LucyferMS
version: 1.0.1
api-version: 1.16
softdepend:
  - HolographicDisplays
depend:
  - FastAsyncWorldEdit
  - Multiverse-Core
  - PlaceholderAPI
  - Vault
  - InterServerTeleport
name: Skyblock
commands:
  debug:
    usage: /debug
  bug:
    usage: /bug
  island:
    usage: /island
    aliases: [ "is", "tcisland" ]
#  testisland:
#    usage: /testisland
#    aliases: ["tis"]
  tempspawn:
    usage: /tempspawn
  worker:
    usage: /worker
    aliases:
      - praca
      - prace
      - profesje
      - profesja
  aworker:
    usage: /aworker
  menu:
    usage: /menu
  vtrades:
    usage: /vtrades
  fly:
    usage: /fly
  checkblock:
    usage: /checkblock
  gamemode:
    usage: /gamemode
    aliases: [gm]