main: pl.trollcraft.Skyblock.Main
authors:
  - Pijok
  - LucyferMS
version: 1.0
api-version: 1.16
depend:
  - FastAsyncWorldEdit
  - Multiverse-Core
  - MVdWPlaceholderAPI
name: Skyblock
commands:
  debug:
    usage: /debug
  island:
    usage: /island
    aliases: [ "is", "tcisland" ]