main: pl.trollcraft.Skyblock.Skyblock
authors:
  - Pijok
  - LucyferMS
version: 1.0
api-version: 1.16
depend:
  - FastAsyncWorldEdit
  - Multiverse-Core
  - PlaceholderAPI
  - Vault
  - InterServerTeleport
name: Skyblock
commands:
  debug:
    usage: /debug
  island:
    usage: /island
    aliases: [ "is", "tcisland" ]
#  testisland:
#    usage: /testisland
#    aliases: ["tis"]
  tempspawn:
    usage: /tempspawn
  worker:
    usage: /worker
  aworker:
    usage: /aworker
  menu:
    usage: /menu
  vtrades:
    usage: /vtrades
  fly:
    usage: /fly